In [2]:
import pandas as pd

In [3]:
# se leen los datos de las maquinas de un dataset local en formato .csv
machine_data = pd.read_csv("machine_data.csv")
machine_data

      machineID   model  age               datetime errorID
0             1  model3   18    1/3/2015 7:00:00 AM  error1
1             1  model3   18    1/3/2015 8:00:00 PM  error3
2             1  model3   18    1/4/2015 6:00:00 AM  error5
3             1  model3   18   1/10/2015 3:00:00 PM  error4
4             1  model3   18  1/22/2015 10:00:00 AM  error4
...         ...     ...  ...                    ...     ...
3914        100  model4    5  11/21/2015 8:00:00 AM  error2
3915        100  model4    5   12/4/2015 2:00:00 AM  error1
3916        100  model4    5   12/8/2015 6:00:00 AM  error2
3917        100  model4    5   12/8/2015 6:00:00 AM  error3
3918        100  model4    5  12/22/2015 3:00:00 AM  error3

[3919 rows x 5 columns]

In [5]:
from sqlalchemy import create_engine

url_machine_telemetry = "postgresql://readonly_user:machine_telemetry_access2026@ep-young-term-apnex782-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
engine = create_engine(url_machine_telemetry)
query = "SELECT * FROM telemetry"

machine_telemetry = pd.read_sql(query, engine)
machine_telemetry

,datetime,machineID,volt,rotate,pressure,vibration
0,1/1/2015 6:00:00 AM,1,176.217853,418.504078,113.077935,45.087686
1,1/1/2015 7:00:00 AM,1,162.879223,402.747490,95.460525,43.413973
2,1/1/2015 8:00:00 AM,1,170.989902,527.349825,75.237905,34.178847
3,1/1/2015 9:00:00 AM,1,162.462833,346.149335,109.248561,41.122144
4,1/1/2015 10:00:00 AM,1,157.610021,435.376873,111.886648,25.990511
...,...,...,...,...,...,...
876095,1/1/2016 2:00:00 AM,100,179.438162,395.222827,102.290715,50.771941
876096,1/1/2016 3:00:00 AM,100,189.617555,446.207972,98.180607,35.123072
876097,1/1/2016 4:00:00 AM,100,192.483414,447.816524,94.132837,48.314561
876098,1/1/2016 5:00:00 AM,100,165.475310,413.771670,104.081073,44.835259
876099,1/1/2016 6:00:00 AM,100,171.336037,496.096870,79.095538,37.845245